package com.company.ipcamera.android.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.company.ipcamera.shared.domain.model.Camera
import com.company.ipcamera.shared.domain.repository.CameraRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

data class CameraAddUiState(
    val name: String = "",
    val url: String = "",
    val username: String = "",
    val password: String = "",
    val isSaving: Boolean = false,
    val error: String? = null,
    val isSuccess: Boolean = false
)

class CameraAddViewModel(
    private val cameraRepository: CameraRepository
) : ViewModel() {

    private val _uiState = MutableStateFlow(CameraAddUiState())
    val uiState: StateFlow<CameraAddUiState> = _uiState.asStateFlow()

    fun updateName(name: String) {
        _uiState.value = _uiState.value.copy(name = name)
    }

    fun updateUrl(url: String) {
        _uiState.value = _uiState.value.copy(url = url)
    }

    fun updateUsername(username: String) {
        _uiState.value = _uiState.value.copy(username = username)
    }

    fun updatePassword(password: String) {
        _uiState.value = _uiState.value.copy(password = password)
    }

    fun saveCamera(onSuccess: () -> Unit) {
        val state = _uiState.value
        if (state.name.isBlank() || state.url.isBlank()) {
            _uiState.value = state.copy(error = "Name and URL are required")
            return
        }

        viewModelScope.launch {
            _uiState.value = state.copy(isSaving = true, error = null)
            try {
                val camera = Camera(
                    id = "", // Will be generated by repository
                    name = state.name,
                    url = state.url,
                    username = state.username.ifBlank { null },
                    password = state.password.ifBlank { null }
                )
                val result = cameraRepository.addCamera(camera)
                result.fold(
                    onSuccess = {
                        _uiState.value = state.copy(
                            isSaving = false,
                            isSuccess = true
                        )
                        onSuccess()
                    },
                    onFailure = { error ->
                        _uiState.value = state.copy(
                            isSaving = false,
                            error = error.message ?: "Failed to add camera"
                        )
                    }
                )
            } catch (e: Exception) {
                _uiState.value = state.copy(
                    isSaving = false,
                    error = e.message ?: "Failed to add camera"
                )
            }
        }
    }

    fun reset() {
        _uiState.value = CameraAddUiState()
    }
}

